[package]
name = "cs-ping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surge-ping = "0.5.2"
reqwest = "0.11.10"
regex = "1.5.5"
tokio = "1.17.0"
futures = "0.3.21"
zzz = { version = "0.1.4", features = ["streams"] }

[profile.release]
strip = true
opt-level = "z"
lto = true
